export const MachineIcons = {
"3 Turbine Wind":"//static.wikitide.net/industrialistwiki/thumb/a/a7/3_Turbine_Wind.png/180px-3_Turbine_Wind.png",
"4 Panel Solar":"//static.wikitide.net/industrialistwiki/thumb/7/7f/4_Panel_Solar.png/180px-4_Panel_Solar.png",
"Advanced Assembler":"//static.wikitide.net/industrialistwiki/thumb/5/55/Advanced_Assembler.png/180px-Advanced_Assembler.png",
"Advanced Coal Drill":"//static.wikitide.net/industrialistwiki/thumb/d/db/Advanced_Coal_Drill.png/180px-Advanced_Coal_Drill.png",
"Advanced Copper Drill":"//static.wikitide.net/industrialistwiki/thumb/5/5f/Advanced_Copper_Drill.png/180px-Advanced_Copper_Drill.png",
"Advanced Diesel Refinery":"//static.wikitide.net/industrialistwiki/thumb/0/0c/Advanced_Diesel_Refinery.png/180px-Advanced_Diesel_Refinery.png",
"Advanced Electric Furnace":"//static.wikitide.net/industrialistwiki/thumb/e/e6/Advanced_Electric_Furnace.png/180px-Advanced_Electric_Furnace.png",
"Advanced MV Pole":"//static.wikitide.net/industrialistwiki/thumb/1/17/Advanced_MV_Pole.png/180px-Advanced_MV_Pole.png",
"Advanced Oil Separator":"//static.wikitide.net/industrialistwiki/thumb/3/32/Advanced_Oil_Separator.png/180px-Advanced_Oil_Separator.png",
"Advanced Oxidation Plant":"//static.wikitide.net/industrialistwiki/thumb/e/e3/Advanced_Oxidation_Plant.png/180px-Advanced_Oxidation_Plant.png",
"Advanced Pollution Meter":"//static.wikitide.net/industrialistwiki/thumb/c/c8/Advanced_Pollution_Meter.png/180px-Advanced_Pollution_Meter.png",
"Advanced Power Rate Meter":"//static.wikitide.net/industrialistwiki/thumb/b/b6/Advanced_Power_Rate_Meter.png/180px-Advanced_Power_Rate_Meter.png",
"Advanced Present Packing Machine":"//static.wikitide.net/industrialistwiki/thumb/e/ea/Advanced_Present_Packing_Machine.png/180px-Advanced_Present_Packing_Machine.png",
"Air Separation Unit":"//static.wikitide.net/industrialistwiki/thumb/e/e4/Air_Separation_Unit.png/180px-Air_Separation_Unit.png",
"Alloyer":"//static.wikitide.net/industrialistwiki/thumb/c/c5/Alloyer.png/180px-Alloyer.png",
"American Oil Rig":"//static.wikitide.net/industrialistwiki/thumb/b/b9/American_Oil_Rig.png/180px-American_Oil_Rig.png",
"AND Gate":"//static.wikitide.net/industrialistwiki/thumb/6/6a/AND_Gate.png/180px-AND_Gate.png",
"Atmospheric Distillation Plant":"//static.wikitide.net/industrialistwiki/thumb/2/29/Atmospheric_Distillation_Plant.png/180px-Atmospheric_Distillation_Plant.png",
"Battery Charger":"//static.wikitide.net/industrialistwiki/thumb/b/b8/Battery_Charger.png/180px-Battery_Charger.png",
"Big Alarm":"//static.wikitide.net/industrialistwiki/thumb/4/4f/Big_Alarm.png/180px-Big_Alarm.png",
"Big Decoration":"//static.wikitide.net/industrialistwiki/thumb/9/94/Big_Decoration.png/180px-Big_Decoration.png",
"Big Liquid Burner":"//static.wikitide.net/industrialistwiki/thumb/7/7b/Big_Liquid_Burner.png/180px-Big_Liquid_Burner.png",
"Billboard":"//static.wikitide.net/industrialistwiki/thumb/9/91/Billboard.png/180px-Billboard.png",
"Blast Furnace":"//static.wikitide.net/industrialistwiki/thumb/e/ed/Blast_Furnace.png/180px-Blast_Furnace.png",
"Blast Furnace MK2":"//static.wikitide.net/industrialistwiki/thumb/9/94/Blast_Furnace_MK2.png/180px-Blast_Furnace_MK2.png",
"Boiler":"//static.wikitide.net/industrialistwiki/thumb/4/46/Boiler.png/180px-Boiler.png",
"Bottling Plant":"//static.wikitide.net/industrialistwiki/thumb/d/d8/Bottling_Plant.png/180px-Bottling_Plant.png",
"Breaker":"//static.wikitide.net/industrialistwiki/thumb/4/4c/Breaker.png/180px-Breaker.png",
"Breaker Box":"//static.wikitide.net/industrialistwiki/thumb/a/a1/Breaker_Box.png/180px-Breaker_Box.png",
"Candy Cane Tree":"//static.wikitide.net/industrialistwiki/thumb/d/d5/Candy_Cane_Tree.png/180px-Candy_Cane_Tree.png",
"Cannon Barrel":"//static.wikitide.net/industrialistwiki/thumb/e/e9/Cannon_Barrel.png/180px-Cannon_Barrel.png",
"Cat Assembler":"//static.wikitide.net/industrialistwiki/thumb/6/66/Cat_Assembler.png/180px-Cat_Assembler.png",
"Chemical Plant":"//static.wikitide.net/industrialistwiki/thumb/6/65/Chemical_Plant.png/180px-Chemical_Plant.png",
"Chemical Reactor":"//static.wikitide.net/industrialistwiki/thumb/7/70/Chemical_Reactor.png/180px-Chemical_Reactor.png",
"Christmas Tree":"//static.wikitide.net/industrialistwiki/thumb/f/f9/Christmas_Tree.png/180px-Christmas_Tree.png",
"Classic Tree":"//static.wikitide.net/industrialistwiki/thumb/d/d5/Classic_Tree.png/180px-Classic_Tree.png",
"Coal Drill":"//static.wikitide.net/industrialistwiki/thumb/d/d3/Coal_Drill.png/180px-Coal_Drill.png",
"Coal Generator":"//static.wikitide.net/industrialistwiki/thumb/b/ba/Coal_Generator.png/180px-Coal_Generator.png",
"Coal Liquefaction Plant":"//static.wikitide.net/industrialistwiki/thumb/c/cc/Coal_Liquefaction_Plant.png/180px-Coal_Liquefaction_Plant.png",
"Coal Power Plant":"//static.wikitide.net/industrialistwiki/thumb/3/34/Coal_Power_Plant.png/180px-Coal_Power_Plant.png",
"Color LED":"//static.wikitide.net/industrialistwiki/thumb/e/ea/Color_LED.png/180px-Color_LED.png",
"Compact Coal Power Plant":"//static.wikitide.net/industrialistwiki/thumb/8/84/Compact_Coal_Power_Plant.png/180px-Compact_Coal_Power_Plant.png",
"Concrete Plant":"//static.wikitide.net/industrialistwiki/thumb/e/e2/Concrete_Plant.png/180px-Concrete_Plant.png",
"Condenser":"//static.wikitide.net/industrialistwiki/thumb/2/21/Condenser.png/180px-Condenser.png",
"Cooling Tower":"//static.wikitide.net/industrialistwiki/thumb/7/79/Cooling_Tower.png/180px-Cooling_Tower.png",
"Copper Drill":"//static.wikitide.net/industrialistwiki/thumb/7/78/Copper_Drill.png/180px-Copper_Drill.png",
"Craft Assembler":"//static.wikitide.net/industrialistwiki/thumb/d/dd/Craft_Assembler.png/180px-Craft_Assembler.png",
"Crude Oil Separator":"//static.wikitide.net/industrialistwiki/thumb/2/2a/Crude_Oil_Separator.png/180px-Crude_Oil_Separator.png",
"CUBE":"null",
"Decoration":"//static.wikitide.net/industrialistwiki/thumb/9/95/Decoration.png/180px-Decoration.png",
"Dev Solar Panel":"//static.wikitide.net/industrialistwiki/thumb/3/30/Dev_Solar_Panel.png/180px-Dev_Solar_Panel.png",
"Diesel Engine Air Input":"//static.wikitide.net/industrialistwiki/thumb/1/1a/Diesel_Engine_Air_Input.png/180px-Diesel_Engine_Air_Input.png",
"Diesel Engine Controller":"//static.wikitide.net/industrialistwiki/thumb/e/ef/Diesel_Engine_Controller.png/180px-Diesel_Engine_Controller.png",
"Diesel Engine Crankshaft":"//static.wikitide.net/industrialistwiki/thumb/3/36/Diesel_Engine_Crankshaft.png/180px-Diesel_Engine_Crankshaft.png",
"Diesel Engine Crankshaft Sideways":"//static.wikitide.net/industrialistwiki/thumb/7/79/Diesel_Engine_Crankshaft_Sideways.png/180px-Diesel_Engine_Crankshaft_Sideways.png",
"Diesel Engine Cylinder":"//static.wikitide.net/industrialistwiki/thumb/7/7a/Diesel_Engine_Cylinder.png/180px-Diesel_Engine_Cylinder.png",
"Diesel Engine Decoration":"//static.wikitide.net/industrialistwiki/thumb/e/ea/Diesel_Engine_Decoration.png/180px-Diesel_Engine_Decoration.png",
"Diesel Engine Exhaust":"//static.wikitide.net/industrialistwiki/thumb/7/75/Diesel_Engine_Exhaust.png/180px-Diesel_Engine_Exhaust.png",
"Diesel Engine Flywheel":"//static.wikitide.net/industrialistwiki/thumb/4/46/Diesel_Engine_Flywheel.png/180px-Diesel_Engine_Flywheel.png",
"Diesel Engine Fuel Input":"//static.wikitide.net/industrialistwiki/thumb/a/ac/Diesel_Engine_Fuel_Input.png/180px-Diesel_Engine_Fuel_Input.png",
"Diesel Engine Generator":"//static.wikitide.net/industrialistwiki/thumb/6/64/Diesel_Engine_Generator.png/180px-Diesel_Engine_Generator.png",
"Diesel Engine Info Panel":"//static.wikitide.net/industrialistwiki/thumb/2/22/Diesel_Engine_Info_Panel.png/180px-Diesel_Engine_Info_Panel.png",
"Diesel Engine Info Panel DEBUG":"//static.wikitide.net/industrialistwiki/thumb/a/a5/Diesel_Engine_Info_Panel_DEBUG.png/180px-Diesel_Engine_Info_Panel_DEBUG.png",
"Diesel Generator":"//static.wikitide.net/industrialistwiki/thumb/f/fa/Diesel_Generator.png/180px-Diesel_Generator.png",
"Diesel Refinery":"//static.wikitide.net/industrialistwiki/thumb/0/06/Diesel_Refinery.png/180px-Diesel_Refinery.png",
"Double MV Battery":"//static.wikitide.net/industrialistwiki/thumb/a/aa/Double_MV_Battery.png/180px-Double_MV_Battery.png",
"Electric Furnace":"//static.wikitide.net/industrialistwiki/thumb/7/7a/Electric_Furnace.png/180px-Electric_Furnace.png",
"Electric Water Heater":"//static.wikitide.net/industrialistwiki/thumb/0/0d/Electric_Water_Heater.png/180px-Electric_Water_Heater.png",
"Electrolysis Plant":"//static.wikitide.net/industrialistwiki/thumb/5/59/Electrolysis_Plant.png/180px-Electrolysis_Plant.png",
"Energy Wheel":"//static.wikitide.net/industrialistwiki/thumb/3/30/Energy_Wheel.png/180px-Energy_Wheel.png",
"Entity Detector":"//static.wikitide.net/industrialistwiki/thumb/f/f9/Entity_Detector.png/180px-Entity_Detector.png",
"Exhaust Stack":"//static.wikitide.net/industrialistwiki/thumb/0/09/Exhaust_Stack.png/180px-Exhaust_Stack.png",
"Fancy Coal Drill":"//static.wikitide.net/industrialistwiki/thumb/2/20/Fancy_Coal_Drill.png/180px-Fancy_Coal_Drill.png",
"Fancy Pollution Meter":"//static.wikitide.net/industrialistwiki/thumb/8/8a/Fancy_Pollution_Meter.png/180px-Fancy_Pollution_Meter.png",
"Farm Harvester":"//static.wikitide.net/industrialistwiki/thumb/a/a1/Farm_Harvester.png/180px-Farm_Harvester.png",
"Festive Coal Power Plant":"//static.wikitide.net/industrialistwiki/thumb/a/a5/Festive_Coal_Power_Plant.png/180px-Festive_Coal_Power_Plant.png",
"Festive Cooling Tower":"//static.wikitide.net/industrialistwiki/thumb/4/4e/Festive_Cooling_Tower.png/180px-Festive_Cooling_Tower.png",
"Festive HMVT":"//static.wikitide.net/industrialistwiki/thumb/4/48/Festive_HMVT.png/180px-Festive_HMVT.png",
"Festive HV Pole":"//static.wikitide.net/industrialistwiki/thumb/9/96/Festive_HV_Pole.png/180px-Festive_HV_Pole.png",
"Festive HV Power Control":"//static.wikitide.net/industrialistwiki/thumb/6/6c/Festive_HV_Power_Control.png/180px-Festive_HV_Power_Control.png",
"Filtration Plant":"//static.wikitide.net/industrialistwiki/thumb/8/81/Filtration_Plant.png/180px-Filtration_Plant.png",
"Firebox":"//static.wikitide.net/industrialistwiki/thumb/e/eb/Firebox.png/180px-Firebox.png",
"Firework":"//static.wikitide.net/industrialistwiki/thumb/2/24/Firework.png/180px-Firework.png",
"Flag":"//static.wikitide.net/industrialistwiki/thumb/7/76/Flag.png/180px-Flag.png",
"Fluid Meter":"//static.wikitide.net/industrialistwiki/thumb/4/42/Fluid_Meter.png/180px-Fluid_Meter.png",
"Fluid Spawner":"//static.wikitide.net/industrialistwiki/thumb/f/f6/Fluid_Spawner.png/180px-Fluid_Spawner.png",
"Fort-Tech Heavy Cannon MK2":"//static.wikitide.net/industrialistwiki/thumb/e/e6/Fort-Tech_Heavy_Cannon_MK2.png/180px-Fort-Tech_Heavy_Cannon_MK2.png",
"Foundry":"//static.wikitide.net/industrialistwiki/thumb/1/19/Foundry.png/180px-Foundry.png",
"Gas Burner":"//static.wikitide.net/industrialistwiki/thumb/5/5b/Gas_Burner.png/180px-Gas_Burner.png",
"Gas Centrifuge":"//static.wikitide.net/industrialistwiki/thumb/3/37/Gas_Centrifuge.png/180px-Gas_Centrifuge.png",
"Gas Refinery":"//static.wikitide.net/industrialistwiki/thumb/8/8c/Gas_Refinery.png/180px-Gas_Refinery.png",
"Gasoline Generator":"//static.wikitide.net/industrialistwiki/thumb/0/0a/Gasoline_Generator.png/180px-Gasoline_Generator.png",
"Geothermal Well":"//static.wikitide.net/industrialistwiki/thumb/c/c8/Geothermal_Well.png/180px-Geothermal_Well.png",
"Gold Acid Refinery":"//static.wikitide.net/industrialistwiki/thumb/8/8f/Gold_Acid_Refinery.png/180px-Gold_Acid_Refinery.png",
"Gold Battery":"//static.wikitide.net/industrialistwiki/thumb/d/de/Gold_Battery.png/180px-Gold_Battery.png",
"Gold Drill":"//static.wikitide.net/industrialistwiki/thumb/8/89/Gold_Drill.png/180px-Gold_Drill.png",
"Gold Fluid Storage Silo":"//static.wikitide.net/industrialistwiki/thumb/3/38/Gold_Fluid_Storage_Silo.png/180px-Gold_Fluid_Storage_Silo.png",
"Gold Fluid Storage Silo Gift":"//static.wikitide.net/industrialistwiki/thumb/e/e0/Gold_Fluid_Storage_Silo_Gift.png/180px-Gold_Fluid_Storage_Silo_Gift.png",
"Gold Item Storage Silo":"//static.wikitide.net/industrialistwiki/thumb/d/db/Gold_Item_Storage_Silo.png/180px-Gold_Item_Storage_Silo.png",
"Gold Item Storage Silo Gift":"//static.wikitide.net/industrialistwiki/thumb/1/15/Gold_Item_Storage_Silo_Gift.png/180px-Gold_Item_Storage_Silo_Gift.png",
"Grinder":"//static.wikitide.net/industrialistwiki/thumb/2/21/Grinder.png/180px-Grinder.png",
"Grinder MK2":"//static.wikitide.net/industrialistwiki/thumb/7/77/Grinder_MK2.png/180px-Grinder_MK2.png",
"Hand Crank":"//static.wikitide.net/industrialistwiki/thumb/5/5d/Hand_Crank.png/180px-Hand_Crank.png",
"Hand Crank MK2":"//static.wikitide.net/industrialistwiki/thumb/3/38/Hand_Crank_MK2.png/180px-Hand_Crank_MK2.png",
"Hand Pump":"//static.wikitide.net/industrialistwiki/thumb/8/88/Hand_Pump.png/180px-Hand_Pump.png",
"Heat Exchanger":"//static.wikitide.net/industrialistwiki/thumb/d/d6/Heat_Exchanger.png/180px-Heat_Exchanger.png",
"High Pressure Turbine":"//static.wikitide.net/industrialistwiki/thumb/1/17/High_Pressure_Turbine.png/180px-High_Pressure_Turbine.png",
"HMVT":"//static.wikitide.net/industrialistwiki/thumb/3/3f/HMVT.png/180px-HMVT.png",
"Hot Water Pump":"//static.wikitide.net/industrialistwiki/thumb/2/2e/Hot_Water_Pump.png/180px-Hot_Water_Pump.png",
"Huge Decoration":"//static.wikitide.net/industrialistwiki/thumb/3/3d/Huge_Decoration.png/180px-Huge_Decoration.png",
"Huge Spotlight":"//static.wikitide.net/industrialistwiki/thumb/9/94/Huge_Spotlight.png/180px-Huge_Spotlight.png",
"Huge Truck Depot":"//static.wikitide.net/industrialistwiki/thumb/4/45/Huge_Truck_Depot.png/180px-Huge_Truck_Depot.png",
"HV Advanced Power Rate Calculator":"//static.wikitide.net/industrialistwiki/thumb/0/0e/HV_Advanced_Power_Rate_Calculator.png/180px-HV_Advanced_Power_Rate_Calculator.png",
"HV Battery":"//static.wikitide.net/industrialistwiki/thumb/2/2e/HV_Battery.png/180px-HV_Battery.png",
"HV Battery MK2":"//static.wikitide.net/industrialistwiki/thumb/f/fd/HV_Battery_MK2.png/180px-HV_Battery_MK2.png",
"HV Pole":"//static.wikitide.net/industrialistwiki/thumb/d/da/HV_Pole.png/180px-HV_Pole.png",
"HV Power Control":"//static.wikitide.net/industrialistwiki/thumb/f/f1/HV_Power_Control.png/180px-HV_Power_Control.png",
"HV Power Dump":"//static.wikitide.net/industrialistwiki/thumb/4/4a/HV_Power_Dump.png/180px-HV_Power_Dump.png",
"HV Transformer":"//static.wikitide.net/industrialistwiki/thumb/0/0d/HV_Transformer.png/180px-HV_Transformer.png",
"Hyper Depot":"//static.wikitide.net/industrialistwiki/thumb/d/d9/Hyper_Depot.png/180px-Hyper_Depot.png",
"Igloo Farm Controller":"//static.wikitide.net/industrialistwiki/thumb/5/5b/Igloo_Farm_Controller.png/180px-Igloo_Farm_Controller.png",
"Incinerator":"//static.wikitide.net/industrialistwiki/thumb/5/5b/Incinerator.png/180px-Incinerator.png",
"Inclined Light":"//static.wikitide.net/industrialistwiki/thumb/4/43/Inclined_Light.png/180px-Inclined_Light.png",
"Inclined Light2":"//static.wikitide.net/industrialistwiki/thumb/8/81/Inclined_Light2.png/180px-Inclined_Light2.png",
"Industrial Diesel Refinery":"//static.wikitide.net/industrialistwiki/thumb/2/25/Industrial_Diesel_Refinery.png/180px-Industrial_Diesel_Refinery.png",
"Industrial Drill":"//static.wikitide.net/industrialistwiki/thumb/d/d0/Industrial_Drill.png/180px-Industrial_Drill.png",
"Industrial Electric Furnace":"//static.wikitide.net/industrialistwiki/thumb/3/3e/Industrial_Electric_Furnace.png/180px-Industrial_Electric_Furnace.png",
"Industrial Firebox":"//static.wikitide.net/industrialistwiki/thumb/a/ab/Industrial_Firebox.png/180px-Industrial_Firebox.png",
"Industrial HV Battery":"//static.wikitide.net/industrialistwiki/thumb/1/19/Industrial_HV_Battery.png/180px-Industrial_HV_Battery.png",
"Industrial Kiln":"//static.wikitide.net/industrialistwiki/thumb/6/69/Industrial_Kiln.png/180px-Industrial_Kiln.png",
"Industrial Oil Separator":"//static.wikitide.net/industrialistwiki/thumb/c/c9/Industrial_Oil_Separator.png/180px-Industrial_Oil_Separator.png",
"Industrial Plastic Molder":"//static.wikitide.net/industrialistwiki/thumb/8/87/Industrial_Plastic_Molder.png/180px-Industrial_Plastic_Molder.png",
"Industrial Present Packing Machine":"//static.wikitide.net/industrialistwiki/thumb/e/e1/Industrial_Present_Packing_Machine.png/180px-Industrial_Present_Packing_Machine.png",
"Industrial Press":"//static.wikitide.net/industrialistwiki/thumb/f/f9/Industrial_Press.png/180px-Industrial_Press.png",
"Industrial Roller":"//static.wikitide.net/industrialistwiki/thumb/9/95/Industrial_Roller.png/180px-Industrial_Roller.png",
"Industrial Sawmill":"//static.wikitide.net/industrialistwiki/thumb/0/07/Industrial_Sawmill.png/180px-Industrial_Sawmill.png",
"Ingot Molder":"//static.wikitide.net/industrialistwiki/thumb/b/bb/Ingot_Molder.png/180px-Ingot_Molder.png",
"Intermediate Pressure Turbine":"//static.wikitide.net/industrialistwiki/thumb/b/b2/Intermediate_Pressure_Turbine.png/180px-Intermediate_Pressure_Turbine.png",
"Iron Drill":"//static.wikitide.net/industrialistwiki/thumb/2/28/Iron_Drill.png/180px-Iron_Drill.png",
"Item Dump":"//static.wikitide.net/industrialistwiki/thumb/7/75/Item_Dump.png/180px-Item_Dump.png",
"Item Meter":"//static.wikitide.net/industrialistwiki/thumb/b/b0/Item_Meter.png/180px-Item_Meter.png",
"Item Spawner":"//static.wikitide.net/industrialistwiki/thumb/f/f8/Item_Spawner.png/180px-Item_Spawner.png",
"Jukebox":"//static.wikitide.net/industrialistwiki/thumb/6/65/Jukebox.png/180px-Jukebox.png",
"Kiln":"//static.wikitide.net/industrialistwiki/thumb/5/58/Kiln.png/180px-Kiln.png",
"Large Diesel Engine":"//static.wikitide.net/industrialistwiki/thumb/f/fd/Large_Diesel_Engine.png/180px-Large_Diesel_Engine.png",
"Large Flag":"//static.wikitide.net/industrialistwiki/thumb/e/ef/Large_Flag.png/180px-Large_Flag.png",
"Large Liquid Truck Depot":"//static.wikitide.net/industrialistwiki/thumb/d/d1/Large_Liquid_Truck_Depot.png/180px-Large_Liquid_Truck_Depot.png",
"Large Pumpjack":"//static.wikitide.net/industrialistwiki/thumb/b/b9/Large_Pumpjack.png/180px-Large_Pumpjack.png",
"Large Turbine":"//static.wikitide.net/industrialistwiki/thumb/5/5a/Large_Turbine.png/180px-Large_Turbine.png",
"Lathe":"//static.wikitide.net/industrialistwiki/thumb/4/44/Lathe.png/180px-Lathe.png",
"Light":"//static.wikitide.net/industrialistwiki/thumb/a/a6/Light.png/180px-Light.png",
"Light2":"//static.wikitide.net/industrialistwiki/thumb/f/fc/Light2.png/180px-Light2.png",
"Lightning Rod":"//static.wikitide.net/industrialistwiki/thumb/6/62/Lightning_Rod.png/180px-Lightning_Rod.png",
"Liquid Boiler":"//static.wikitide.net/industrialistwiki/thumb/8/8f/Liquid_Boiler.png/180px-Liquid_Boiler.png",
"Liquid Burner":"//static.wikitide.net/industrialistwiki/thumb/f/f3/Liquid_Burner.png/180px-Liquid_Burner.png",
"Liquid Dump":"//static.wikitide.net/industrialistwiki/thumb/e/e5/Liquid_Dump.png/180px-Liquid_Dump.png",
"Liquid Truck Depot":"//static.wikitide.net/industrialistwiki/thumb/a/a7/Liquid_Truck_Depot.png/180px-Liquid_Truck_Depot.png",
"Lithium Brine Extractor":"//static.wikitide.net/industrialistwiki/thumb/c/cf/Lithium_Brine_Extractor.png/180px-Lithium_Brine_Extractor.png",
"Lithium Ore Drill":"//static.wikitide.net/industrialistwiki/thumb/1/1d/Lithium_Ore_Drill.png/180px-Lithium_Ore_Drill.png",
"LNG Plant":"//static.wikitide.net/industrialistwiki/thumb/6/66/LNG_Plant.png/180px-LNG_Plant.png",
"Logic Adder":"//static.wikitide.net/industrialistwiki/thumb/d/d9/Logic_Adder.png/180px-Logic_Adder.png",
"Logic Assembler":"//static.wikitide.net/industrialistwiki/thumb/2/2b/Logic_Assembler.png/180px-Logic_Assembler.png",
"Logic Breaker":"//static.wikitide.net/industrialistwiki/thumb/a/ab/Logic_Breaker.png/180px-Logic_Breaker.png",
"Logic Button":"//static.wikitide.net/industrialistwiki/thumb/4/4f/Logic_Button.png/180px-Logic_Button.png",
"Logic Buzzer":"//static.wikitide.net/industrialistwiki/thumb/d/da/Logic_Buzzer.png/180px-Logic_Buzzer.png",
"Logic Clock":"//static.wikitide.net/industrialistwiki/thumb/a/ac/Logic_Clock.png/180px-Logic_Clock.png",
"Logic Dabble":"//static.wikitide.net/industrialistwiki/thumb/c/c5/Logic_Dabble.png/180px-Logic_Dabble.png",
"Logic Delay":"//static.wikitide.net/industrialistwiki/thumb/1/16/Logic_Delay.png/180px-Logic_Delay.png",
"Logic Fluid Pipe Valve":"//static.wikitide.net/industrialistwiki/thumb/6/66/Logic_Fluid_Pipe_Valve.png/180px-Logic_Fluid_Pipe_Valve.png",
"Logic Item Pipe Valve":"//static.wikitide.net/industrialistwiki/thumb/6/6b/Logic_Item_Pipe_Valve.png/180px-Logic_Item_Pipe_Valve.png",
"Logic Knot":"//static.wikitide.net/industrialistwiki/thumb/6/69/Logic_Knot.png/180px-Logic_Knot.png",
"Logic Memory":"//static.wikitide.net/industrialistwiki/thumb/9/90/Logic_Memory.png/180px-Logic_Memory.png",
"Logic Pole":"//static.wikitide.net/industrialistwiki/thumb/d/d2/Logic_Pole.png/180px-Logic_Pole.png",
"Logic Pulse":"//static.wikitide.net/industrialistwiki/thumb/0/00/Logic_Pulse.png/180px-Logic_Pulse.png",
"Logic Random":"//static.wikitide.net/industrialistwiki/thumb/f/f6/Logic_Random.png/180px-Logic_Random.png",
"Logic Relay":"//static.wikitide.net/industrialistwiki/thumb/8/87/Logic_Relay.png/180px-Logic_Relay.png",
"Logic Switch":"//static.wikitide.net/industrialistwiki/thumb/4/48/Logic_Switch.png/180px-Logic_Switch.png",
"Low Pressure Turbine":"//static.wikitide.net/industrialistwiki/thumb/6/66/Low_Pressure_Turbine.png/180px-Low_Pressure_Turbine.png",
"LV Pole":"//static.wikitide.net/industrialistwiki/thumb/c/c2/LV_Pole.png/180px-LV_Pole.png",
"Medium Fluid Storage Silo":"//static.wikitide.net/industrialistwiki/thumb/f/fb/Medium_Fluid_Storage_Silo.png/180px-Medium_Fluid_Storage_Silo.png",
"Medium Item Storage Silo":"//static.wikitide.net/industrialistwiki/thumb/8/85/Medium_Item_Storage_Silo.png/180px-Medium_Item_Storage_Silo.png",
"Metal Sign":"//static.wikitide.net/industrialistwiki/thumb/a/ad/Metal_Sign.png/180px-Metal_Sign.png",
"Mineshaft Drill":"//static.wikitide.net/industrialistwiki/thumb/3/37/Mineshaft_Drill.png/180px-Mineshaft_Drill.png",
"MV Battery":"//static.wikitide.net/industrialistwiki/thumb/c/ce/MV_Battery.png/180px-MV_Battery.png",
"MV Pole":"//static.wikitide.net/industrialistwiki/thumb/3/3a/MV_Pole.png/180px-MV_Pole.png",
"NAND Gate":"//static.wikitide.net/industrialistwiki/thumb/1/17/NAND_Gate.png/180px-NAND_Gate.png",
"Natural Gas Well":"//static.wikitide.net/industrialistwiki/thumb/7/73/Natural_Gas_Well.png/180px-Natural_Gas_Well.png",
"NOR Gate":"//static.wikitide.net/industrialistwiki/thumb/9/9b/NOR_Gate.png/180px-NOR_Gate.png",
"NOT Gate":"//static.wikitide.net/industrialistwiki/thumb/9/92/NOT_Gate.png/180px-NOT_Gate.png",
"Nuclear Power Plant":"//static.wikitide.net/industrialistwiki/thumb/4/46/Nuclear_Power_Plant.png/180px-Nuclear_Power_Plant.png",
"OG Oil Rig":"//static.wikitide.net/industrialistwiki/thumb/d/d2/OG_Oil_Rig.png/180px-OG_Oil_Rig.png",
"OG Research Station":"//static.wikitide.net/industrialistwiki/thumb/2/26/OG_Research_Station.png/180px-OG_Research_Station.png",
"Oil Fracking Tower":"//static.wikitide.net/industrialistwiki/thumb/c/ce/Oil_Fracking_Tower.png/180px-Oil_Fracking_Tower.png",
"Oil Rig":"//static.wikitide.net/industrialistwiki/thumb/c/c3/Oil_Rig.png/180px-Oil_Rig.png",
"OR Gate":"//static.wikitide.net/industrialistwiki/thumb/4/4c/OR_Gate.png/180px-OR_Gate.png",
"Ore Enrichment Facility":"//static.wikitide.net/industrialistwiki/thumb/f/f3/Ore_Enrichment_Facility.png/180px-Ore_Enrichment_Facility.png",
"Oxidation Plant":"//static.wikitide.net/industrialistwiki/thumb/a/a5/Oxidation_Plant.png/180px-Oxidation_Plant.png",
"Paper Mill":"//static.wikitide.net/industrialistwiki/thumb/6/62/Paper_Mill.png/180px-Paper_Mill.png",
"Plastic Molding Machine":"//static.wikitide.net/industrialistwiki/thumb/9/96/Plastic_Molding_Machine.png/180px-Plastic_Molding_Machine.png",
"Plastic Production Facility":"//static.wikitide.net/industrialistwiki/thumb/7/70/Plastic_Production_Facility.png/180px-Plastic_Production_Facility.png",
"Plastic Refinery":"//static.wikitide.net/industrialistwiki/thumb/b/b8/Plastic_Refinery.png/180px-Plastic_Refinery.png",
"Polisher":"//static.wikitide.net/industrialistwiki/thumb/f/f9/Polisher.png/180px-Polisher.png",
"Pollution Gate":"//static.wikitide.net/industrialistwiki/thumb/7/7c/Pollution_Gate.png/180px-Pollution_Gate.png",
"Pollution Meter":"//static.wikitide.net/industrialistwiki/thumb/3/31/Pollution_Meter.png/180px-Pollution_Meter.png",
"Power Control":"//static.wikitide.net/industrialistwiki/thumb/3/37/Power_Control.png/180px-Power_Control.png",
"Power Dump":"//static.wikitide.net/industrialistwiki/thumb/4/40/Power_Dump.png/180px-Power_Dump.png",
"Power Rate Calculator":"//static.wikitide.net/industrialistwiki/thumb/3/37/Power_Rate_Calculator.png/180px-Power_Rate_Calculator.png",
"Power Rate Calculator2":"//static.wikitide.net/industrialistwiki/thumb/b/b5/Power_Rate_Calculator2.png/180px-Power_Rate_Calculator2.png",
"Power Rate Calculator3":"//static.wikitide.net/industrialistwiki/thumb/c/c2/Power_Rate_Calculator3.png/180px-Power_Rate_Calculator3.png",
"Precision Assembler":"//static.wikitide.net/industrialistwiki/thumb/2/2e/Precision_Assembler.png/180px-Precision_Assembler.png",
"Presents Decoration":"//static.wikitide.net/industrialistwiki/thumb/2/2f/Presents_Decoration.png/180px-Presents_Decoration.png",
"Presents Packing Machine":"//static.wikitide.net/industrialistwiki/thumb/3/30/Presents_Packing_Machine.png/180px-Presents_Packing_Machine.png",
"Press":"//static.wikitide.net/industrialistwiki/thumb/c/ce/Press.png/180px-Press.png",
"Press MK2":"//static.wikitide.net/industrialistwiki/thumb/7/7f/Press_MK2.png/180px-Press_MK2.png",
"Pressurized Water Filter":"//static.wikitide.net/industrialistwiki/thumb/c/c3/Pressurized_Water_Filter.png/180px-Pressurized_Water_Filter.png",
"Quarry":"//static.wikitide.net/industrialistwiki/thumb/2/28/Quarry.png/180px-Quarry.png",
"Raw Mill":"//static.wikitide.net/industrialistwiki/thumb/0/09/Raw_Mill.png/180px-Raw_Mill.png",
"Real Dev Solar Panel":"//static.wikitide.net/industrialistwiki/thumb/f/f9/Real_Dev_Solar_Panel.png/180px-Real_Dev_Solar_Panel.png",
"Research Station1":"//static.wikitide.net/industrialistwiki/thumb/7/74/Research_Station1.png/180px-Research_Station1.png",
"Research Station2":"//static.wikitide.net/industrialistwiki/thumb/a/a8/Research_Station2.png/180px-Research_Station2.png",
"Research Station2 (old)":"//static.wikitide.net/industrialistwiki/thumb/c/ca/Research_Station2_%28old%29.png/180px-Research_Station2_%28old%29.png",
"Research Station3":"//static.wikitide.net/industrialistwiki/thumb/4/4a/Research_Station3.png/180px-Research_Station3.png",
"Research Station4":"//static.wikitide.net/industrialistwiki/thumb/f/f4/Research_Station4.png/180px-Research_Station4.png",
"Research Tracking Panel":"//static.wikitide.net/industrialistwiki/thumb/4/43/Research_Tracking_Panel.png/180px-Research_Tracking_Panel.png",
"Residue Refinery":"//static.wikitide.net/industrialistwiki/thumb/6/6f/Residue_Refinery.png/180px-Residue_Refinery.png",
"Resistor":"//static.wikitide.net/industrialistwiki/thumb/1/15/Resistor.png/180px-Resistor.png",
"RGBLLED":"//static.wikitide.net/industrialistwiki/thumb/3/38/RGBLLED.png/180px-RGBLLED.png",
"Roller":"//static.wikitide.net/industrialistwiki/thumb/3/3c/Roller.png/180px-Roller.png",
"Roller MK2":"//static.wikitide.net/industrialistwiki/thumb/6/65/Roller_MK2.png/180px-Roller_MK2.png",
"RTG":"//static.wikitide.net/industrialistwiki/thumb/8/87/RTG.png/180px-RTG.png",
"Rusty Battery":"//static.wikitide.net/industrialistwiki/thumb/1/1c/Rusty_Battery.png/180px-Rusty_Battery.png",
"Sand Excavator":"//static.wikitide.net/industrialistwiki/thumb/8/84/Sand_Excavator.png/180px-Sand_Excavator.png",
"Satellite Dish":"//static.wikitide.net/industrialistwiki/thumb/4/41/Satellite_Dish.png/180px-Satellite_Dish.png",
"Satellite Dish Controller":"//static.wikitide.net/industrialistwiki/thumb/b/b8/Satellite_Dish_Controller.png/180px-Satellite_Dish_Controller.png",
"Sawmill":"//static.wikitide.net/industrialistwiki/thumb/4/4a/Sawmill.png/180px-Sawmill.png",
"Scrubber":"//static.wikitide.net/industrialistwiki/thumb/e/e9/Scrubber.png/180px-Scrubber.png",
"Seven Segment Display":"//static.wikitide.net/industrialistwiki/thumb/a/a7/Seven_Segment_Display.png/180px-Seven_Segment_Display.png",
"Sign":"//static.wikitide.net/industrialistwiki/thumb/5/5d/Sign.png/180px-Sign.png",
"Sleigh Depot":"//static.wikitide.net/industrialistwiki/thumb/f/fb/Sleigh_Depot.png/180px-Sleigh_Depot.png",
"Small Fluid Storage Silo":"//static.wikitide.net/industrialistwiki/thumb/1/18/Small_Fluid_Storage_Silo.png/180px-Small_Fluid_Storage_Silo.png",
"Small Item Storage Silo":"//static.wikitide.net/industrialistwiki/thumb/a/a8/Small_Item_Storage_Silo.png/180px-Small_Item_Storage_Silo.png",
"Small MV Pole":"//static.wikitide.net/industrialistwiki/thumb/7/77/Small_MV_Pole.png/180px-Small_MV_Pole.png",
"Small Plate":"//static.wikitide.net/industrialistwiki/thumb/3/36/Small_Plate.png/180px-Small_Plate.png",
"Small Turbine":"//static.wikitide.net/industrialistwiki/thumb/e/ee/Small_Turbine.png/180px-Small_Turbine.png",
"Snow Globe":"//static.wikitide.net/industrialistwiki/thumb/b/b7/Snow_Globe.png/180px-Snow_Globe.png",
"Snow Globe2":"//static.wikitide.net/industrialistwiki/thumb/6/66/Snow_Globe2.png/180px-Snow_Globe2.png",
"Snowman":"//static.wikitide.net/industrialistwiki/thumb/c/c7/Snowman.png/180px-Snowman.png",
"Soil Excavator":"//static.wikitide.net/industrialistwiki/thumb/3/30/Soil_Excavator.png/180px-Soil_Excavator.png",
"Solar Farm1":"//static.wikitide.net/industrialistwiki/thumb/b/be/Solar_Farm1.png/180px-Solar_Farm1.png",
"Solar Heater":"//static.wikitide.net/industrialistwiki/thumb/4/4a/Solar_Heater.png/180px-Solar_Heater.png",
"Solar Panel":"//static.wikitide.net/industrialistwiki/thumb/5/5d/Solar_Panel.png/180px-Solar_Panel.png",
"Solar Panel2":"//static.wikitide.net/industrialistwiki/thumb/b/b0/Solar_Panel2.png/180px-Solar_Panel2.png",
"Solar Panel3":"//static.wikitide.net/industrialistwiki/thumb/2/22/Solar_Panel3.png/180px-Solar_Panel3.png",
"Spotlight":"//static.wikitide.net/industrialistwiki/thumb/3/32/Spotlight.png/180px-Spotlight.png",
"Spotlight Tower":"//static.wikitide.net/industrialistwiki/thumb/6/6e/Spotlight_Tower.png/180px-Spotlight_Tower.png",
"Steam Condenser":"//static.wikitide.net/industrialistwiki/thumb/e/eb/Steam_Condenser.png/180px-Steam_Condenser.png",
"Steam Cracking Plant":"//static.wikitide.net/industrialistwiki/thumb/a/ab/Steam_Cracking_Plant.png/180px-Steam_Cracking_Plant.png",
"Steam Turbine":"//static.wikitide.net/industrialistwiki/thumb/3/30/Steam_Turbine.png/180px-Steam_Turbine.png",
"Tall Light":"//static.wikitide.net/industrialistwiki/thumb/2/26/Tall_Light.png/180px-Tall_Light.png",
"Time Gate":"//static.wikitide.net/industrialistwiki/thumb/5/5b/Time_Gate.png/180px-Time_Gate.png",
"Time Tracker":"//static.wikitide.net/industrialistwiki/thumb/7/77/Time_Tracker.png/180px-Time_Tracker.png",
"Tree":"//static.wikitide.net/industrialistwiki/thumb/a/ac/Tree.png/180px-Tree.png",
"Tree Farm Controller":"//static.wikitide.net/industrialistwiki/thumb/0/04/Tree_Farm_Controller.png/180px-Tree_Farm_Controller.png",
"Tree Farm Output":"//static.wikitide.net/industrialistwiki/thumb/1/1e/Tree_Farm_Output.png/180px-Tree_Farm_Output.png",
"Tree Farm Sprinkler":"//static.wikitide.net/industrialistwiki/thumb/6/61/Tree_Farm_Sprinkler.png/180px-Tree_Farm_Sprinkler.png",
"Tree Farm Water Tank":"//static.wikitide.net/industrialistwiki/thumb/b/b6/Tree_Farm_Water_Tank.png/180px-Tree_Farm_Water_Tank.png",
"Tree Scrubber":"//static.wikitide.net/industrialistwiki/thumb/d/d5/Tree_Scrubber.png/180px-Tree_Scrubber.png",
"Trommel":"//static.wikitide.net/industrialistwiki/thumb/1/1c/Trommel.png/180px-Trommel.png",
"Truck Depot":"//static.wikitide.net/industrialistwiki/thumb/7/77/Truck_Depot.png/180px-Truck_Depot.png",
"Turbine Generator":"//static.wikitide.net/industrialistwiki/thumb/b/ba/Turbine_Generator.png/180px-Turbine_Generator.png",
"Turbine Input":"//static.wikitide.net/industrialistwiki/thumb/a/ae/Turbine_Input.png/180px-Turbine_Input.png",
"Turbine Output":"//static.wikitide.net/industrialistwiki/thumb/8/86/Turbine_Output.png/180px-Turbine_Output.png",
"Underground Waste Facility":"//static.wikitide.net/industrialistwiki/thumb/4/43/Underground_Waste_Facility.png/180px-Underground_Waste_Facility.png",
"Uranium Drill":"//static.wikitide.net/industrialistwiki/thumb/2/2b/Uranium_Drill.png/180px-Uranium_Drill.png",
"Van Depot":"//static.wikitide.net/industrialistwiki/thumb/2/26/Van_Depot.png/180px-Van_Depot.png",
"Vaporizer":"//static.wikitide.net/industrialistwiki/thumb/c/ca/Vaporizer.png/180px-Vaporizer.png",
"Vertical Heat Exchanger":"//static.wikitide.net/industrialistwiki/thumb/2/2a/Vertical_Heat_Exchanger.png/180px-Vertical_Heat_Exchanger.png",
"Wall":"//static.wikitide.net/industrialistwiki/thumb/9/96/Wall.png/180px-Wall.png",
"Wall Door":"//static.wikitide.net/industrialistwiki/thumb/6/65/Wall_Door.png/180px-Wall_Door.png",
"Wall Fence":"//static.wikitide.net/industrialistwiki/thumb/b/b3/Wall_Fence.png/180px-Wall_Fence.png",
"Wall Junction":"//static.wikitide.net/industrialistwiki/thumb/0/0a/Wall_Junction.png/180px-Wall_Junction.png",
"Wall Section":"//static.wikitide.net/industrialistwiki/thumb/7/79/Wall_Section.png/180px-Wall_Section.png",
"Wall Straight":"//static.wikitide.net/industrialistwiki/thumb/1/13/Wall_Straight.png/180px-Wall_Straight.png",
"Wall Turn":"//static.wikitide.net/industrialistwiki/thumb/0/03/Wall_Turn.png/180px-Wall_Turn.png",
"Water Pump":"//static.wikitide.net/industrialistwiki/thumb/e/e9/WaterPump.png/180px-WaterPump.png",
"Water Pump2":"//static.wikitide.net/industrialistwiki/thumb/c/cf/Water_Pump2.png/180px-Water_Pump2.png",
"Water Treatment Plant":"//static.wikitide.net/industrialistwiki/thumb/7/7e/Water_Treatment_Plant.png/180px-Water_Treatment_Plant.png",
"Weird Decoration":"//static.wikitide.net/industrialistwiki/thumb/3/34/Weird_Decoration.png/180px-Weird_Decoration.png",
"White LED":"//static.wikitide.net/industrialistwiki/thumb/4/48/White_LED.png/180px-White_LED.png",
"Wide Gold Item Storage Silo":"//static.wikitide.net/industrialistwiki/thumb/0/07/Wide_Gold_Item_Storage_Silo.png/180px-Wide_Gold_Item_Storage_Silo.png",
"Wind Turbine1":"//static.wikitide.net/industrialistwiki/thumb/2/27/Wind_Turbine1.png/180px-Wind_Turbine1.png",
"Wind Turbine2":"//static.wikitide.net/industrialistwiki/thumb/8/8e/Wind_Turbine2.png/180px-Wind_Turbine2.png",
"Wind Turbine3":"//static.wikitide.net/industrialistwiki/thumb/1/1e/Wind_Turbine3.png/180px-Wind_Turbine3.png",
"Wind Turbine4":"//static.wikitide.net/industrialistwiki/thumb/7/73/Wind_Turbine4.png/180px-Wind_Turbine4.png",
"XOR Gate":"//static.wikitide.net/industrialistwiki/thumb/3/39/XOR_Gate.png/180px-XOR_Gate.png"
}